name: PR Review Requested

on:
  pull_request_target:
    types: [review_requested]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "status: waiting for author"
      - run: |
          echo "Don't worry about if the previous step failed."
          echo "See https://github.com/actions-ecosystem/action-remove-labels/issues/221."

permissions:
  pull-requests: write
